language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.4
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.1

before_install: ./travis-ci/before_install.sh
before_script: ./travis-ci/before_script.sh
script: ./travis-ci/script.sh
after_failure: ./travis-ci/after_failure.sh
